### ISSUE TITLE
Upgrading Metabase to v0.46 Latest

### ISSUE THREAD

**Issue by fhziliotti** [relferreira/metabase-sparksql-databricks-driver#17]
After updating Metabase to version 0.46.0 the metabase-sparksql-databricks-driver plugin is showing the error below:

```
An error occurred in your query
No method in multimethod 'connection-details->spec' for dispatch value: :sparksql-databricks
```

Could you help us?

**Comment by erkiesken** [comment]
Same issue happing for us. 0.46.0 with 1.6.0 of this plugin:

> :error "No method in multimethod 'connection-details->spec' for dispatch value: :sparksql-databricks",

**Comment by davidhariri** [comment]
Hi there, I also have this same problem. I would help fix it, but I don't know Clojure or Java!

**Comment by alxsbn** [comment]
Same issue here. We have this error message in our MB logs 
```
Warning: Driver :sparksql-databricks is using Honey SQL 1. This method was deprecated in 0.46.0 and will be removed in a future release.
```

**Comment by alxsbn** [comment]
@relferreira Any news on this? It's not linked but I see that Metabase include Databricks driver on their roadmap (above 6 month), are you in contact with them?

**Comment by relferreira** [comment]
Hello everybody. 
I'm really sorry, but I don't use Databricks and Metabase in my daily job anymore, so it's hard to find some time to keep this driver updated, but I'll try fixing this in the next few days.

**Comment by lydiw** [comment]
Hello everybody, 

I have  just created a new [PR](https://github.com/relferreira/metabase-sparksql-databricks-driver/pull/18) for supporting Metabase v0.46. 
Unfortunately, I don't have enough time to update the Docker file.
I have based on README from this https://github.com/metabase/sudoku-driver repo in order to build the library.

**Comment by alxsbn** [comment]
Once again, any news on it ?

**Comment by opus-42** [comment]
Hello @bjgbeelen or @relferreira, would it be possible to release a new package version for the >= 0.46.0 versions  ? 🙏
