### ISSUE TITLE
local build is failing 

### ISSUE THREAD

**Issue by kRahul123** [relferreira/metabase-sparksql-databricks-driver#21]
**My local build is failing when i run the docker build command. Below is the log.**

`#22 26.69 2023-07-19 19:20:04,379 tools.deps worker 2 DEBUG AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
#22 26.69 2023-07-19 19:20:04,380 tools.deps worker 2 DEBUG org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
#22 30.84 Build driver :sparksql-databricks (edition = :oss, options = {:project-dir "/build/driver", :target-dir "./target"})
#22 30.84   Clean
#22 30.84     Delete /build/driver/target/jar if exists
#22 30.84       Don't need to delete /build/driver/target/jar, file does not exist.
#22 30.84     Delete ./target/sparksql-databricks.metabase-driver.jar if exists
#22 30.84       Don't need to delete ./target/sparksql-databricks.metabase-driver.jar, file does not exist.
#22 30.84   Copy :sparksql-databricks source files
#22 30.88     Copying files in ["/build/driver/src" "/build/driver/resources"]
#22 30.94     Copied files in 2 directories in 98 ms.
#22 30.94   Compile clojure source files
#22 30.96     Compiling Clojure source files in ["/build/driver/src" "/build/driver/resources"] to /build/driver/target/jar
#22 30.96     Create directory /build/driver/target/jar if it does not exist
#22 30.96       /build/driver/target/jar already exists.
#22 30.96     Compiling namespaces [metabase.driver.connection metabase.driver.FixedSparkDriver metabase.driver.hive-like metabase.driver.sparksql-databricks]
#22 31.40 Step failed: Syntax error macroexpanding at (metabase/driver/hive_like.clj:1:1).
#22 31.72 {:via
#22 31.72  [{:type clojure.lang.Compiler$CompilerException,
#22 31.72    :message "Syntax error macroexpanding at (metabase/driver/hive_like.clj:1:1).",
#22 31.72    :data #:clojure.error{:phase :execution, :line 1, :column 1, :source "metabase/driver/hive_like.clj"},
#22 31.72    :at [clojure.lang.Compiler load "Compiler.java" 7665]}
#22 31.72   {:type java.io.FileNotFoundException,
#22 31.72    :message "Could not locate honey/sql__init.class, honey/sql.clj or honey/sql.cljc on classpath.",
#22 31.72    :at [clojure.lang.RT load "RT.java" 462]}],
#22 31.72  :trace
#22 31.72  [[clojure.lang.RT load "RT.java" 462]
#22 31.72   [clojure.lang.RT load "RT.java" 424]
#22 31.72   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
#22 31.72   [clojure.core$load invokeStatic "core.clj" 6160]
#22 31.72   [clojure.core$load doInvoke "core.clj" 6144]
#22 31.72   [clojure.lang.RestFn invoke "RestFn.java" 408]
#22 31.72   [clojure.core$load_one invokeStatic "core.clj" 5933]
#22 31.72   [clojure.core$load_one invoke "core.clj" 5928]
#22 31.72   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
#22 31.72   [clojure.core$load_lib invokeStatic "core.clj" 5974]
#22 31.72   [clojure.core$load_lib doInvoke "core.clj" 5953]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 142]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 669]
#22 31.72   [clojure.core$load_libs invokeStatic "core.clj" 6016]
#22 31.72   [clojure.core$load_libs doInvoke "core.clj" 6000]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 669]
#22 31.72   [clojure.core$require invokeStatic "core.clj" 6038]
#22 31.72   [clojure.core$require doInvoke "core.clj" 6038]
#22 31.72   [clojure.lang.RestFn invoke "RestFn.java" 1789]
#22 31.72   [metabase.driver.hive_like$eval8495$loading__6789__auto____8496 invoke "hive_like.clj" 1]
#22 31.72   [metabase.driver.hive_like$eval8495 invokeStatic "hive_like.clj" 1]
#22 31.72   [metabase.driver.hive_like$eval8495 invoke "hive_like.clj" 1]
#22 31.72   [clojure.lang.Compiler eval "Compiler.java" 7194]
#22 31.72   [clojure.lang.Compiler eval "Compiler.java" 7183]
#22 31.72   [clojure.lang.Compiler load "Compiler.java" 7653]
#22 31.72   [clojure.lang.RT loadResourceScript "RT.java" 381]
#22 31.72   [clojure.lang.RT loadResourceScript "RT.java" 372]
#22 31.72   [clojure.lang.RT load "RT.java" 459]
#22 31.72   [clojure.lang.RT load "RT.java" 424]
#22 31.72   [clojure.core$load$fn__6908 invoke "core.clj" 6161]
#22 31.72   [clojure.core$load invokeStatic "core.clj" 6160]
#22 31.72   [clojure.core$load doInvoke "core.clj" 6144]
#22 31.72   [clojure.lang.RestFn invoke "RestFn.java" 408]
#22 31.72   [clojure.core$load_one invokeStatic "core.clj" 5933]
#22 31.72   [clojure.core$load_one invoke "core.clj" 5928]
#22 31.72   [clojure.core$load_lib$fn__6850 invoke "core.clj" 5975]
#22 31.72   [clojure.core$load_lib invokeStatic "core.clj" 5974]
#22 31.72   [clojure.core$load_lib doInvoke "core.clj" 5953]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 142]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 669]
#22 31.72   [clojure.core$load_libs invokeStatic "core.clj" 6016]
#22 31.72   [clojure.core$load_libs doInvoke "core.clj" 6000]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 669]
#22 31.72   [clojure.core$require invokeStatic "core.clj" 6038]
#22 31.72   [clojure.core$require doInvoke "core.clj" 6038]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 667]
#22 31.72   [clojure.core$serialized_require invokeStatic "core.clj" 6114]
#22 31.72   [clojure.core$serialized_require doInvoke "core.clj" 6108]
#22 31.72   [clojure.lang.RestFn invoke "RestFn.java" 408]
#22 31.72   [clojure.lang.Var invoke "Var.java" 384]
#22 31.72   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_$fn__4570$fn__4571
#22 31.72    invoke
#22 31.72    "compile_source_files.clj"
#22 31.72    50]
#22 31.72   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_$fn__4570 invoke "compile_source_files.clj" 48]
#22 31.72   [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
#22 31.72   [metabuild_common.steps$do_step invoke "steps.clj" 79]
#22 31.72   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_ invokeStatic "compile_source_files.clj" 40]
#22 31.72   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_ invoke "compile_source_files.clj" 39]
#22 31.72   [build_drivers.build_driver$build_driver_BANG_$fn__7955 invoke "build_driver.clj" 32]
#22 31.72   [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
#22 31.72   [metabuild_common.steps$do_step invoke "steps.clj" 79]
#22 31.72   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 29]
#22 31.72   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 14]
#22 31.72   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 17]
#22 31.72   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 14]
#22 31.72   [clojure.lang.AFn applyToHelper "AFn.java" 154]
#22 31.72   [clojure.lang.AFn applyTo "AFn.java" 144]
#22 31.72   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 667]
#22 31.72   [clojure.core$apply invoke "core.clj" 662]
#22 31.72   [clojure.run.exec$exec invokeStatic "exec.clj" 48]
#22 31.72   [clojure.run.exec$exec doInvoke "exec.clj" 39]
#22 31.72   [clojure.lang.RestFn invoke "RestFn.java" 423]
#22 31.72   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
#22 31.72   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
#22 31.72   [clojure.run.exec$_main doInvoke "exec.clj" 139]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.72   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.72   [clojure.core$apply invokeStatic "core.clj" 667]
#22 31.72   [clojure.main$main_opt invokeStatic "main.clj" 514]
#22 31.72   [clojure.main$main_opt invoke "main.clj" 510]
#22 31.72   [clojure.main$main invokeStatic "main.clj" 664]
#22 31.72   [clojure.main$main doInvoke "main.clj" 616]
#22 31.72   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.72   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.72   [clojure.main main "main.java" 40]],
#22 31.72  :cause "Could not locate honey/sql__init.class, honey/sql.clj or honey/sql.cljc on classpath.",
#22 31.72  :phase :execution}
#22 31.72     Step "Compile clojure source files" failed with error "Syntax error macroexpanding at (metabase/driver/hive_like.clj:1:1)."
#22 31.72 What would you like to do?
#22 31.72 [T]ry this step again
#22 31.72 [F]ail -- pass the failure of this step to the parent step (which can be retried)
#22 31.72 [S]kip this step
#22 31.72 [R]EPL -- open a REPL so you can debug things
#22 31.72 [Q]uit the build script (or return to the top level if running from the REPL) [T/F/S/R/Q] Step failed: 
#22 31.81 {:via [{:type java.lang.NullPointerException, :at [clojure.string$trim invokeStatic "string.clj" 239]}],
#22 31.81  :trace
#22 31.81  [[clojure.string$trim invokeStatic "string.clj" 239]
#22 31.81   [clojure.string$trim invoke "string.clj" 235]
#22 31.81   [metabuild_common.input$read_line_with_prompt invokeStatic "input.clj" 28]
#22 31.81   [metabuild_common.input$read_line_with_prompt doInvoke "input.clj" 15]
#22 31.81   [clojure.lang.RestFn applyTo "RestFn.java" 139]
#22 31.81   [clojure.core$apply invokeStatic "core.clj" 673]
#22 31.81   [clojure.core$apply invoke "core.clj" 662]
#22 31.81   [metabuild_common.input$letter_options_prompt invokeStatic "input.clj" 59]
#22 31.81   [metabuild_common.input$letter_options_prompt doInvoke "input.clj" 47]
#22 31.81   [clojure.lang.RestFn invoke "RestFn.java" 425]
#22 31.81   [metabuild_common.steps$handle_step_failure_interactive invokeStatic "steps.clj" 49]
#22 31.81   [metabuild_common.steps$handle_step_failure_interactive invoke "steps.clj" 45]
#22 31.81   [metabuild_common.steps$do_step invokeStatic "steps.clj" 91]
#22 31.81   [metabuild_common.steps$do_step invoke "steps.clj" 79]
#22 31.81   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_ invokeStatic "compile_source_files.clj" 40]
#22 31.81   [build_drivers.compile_source_files$compile_clojure_source_files_BANG_ invoke "compile_source_files.clj" 39]
#22 31.81   [build_drivers.build_driver$build_driver_BANG_$fn__7955 invoke "build_driver.clj" 32]
#22 31.81   [metabuild_common.steps$do_step invokeStatic "steps.clj" 85]
#22 31.81   [metabuild_common.steps$do_step invoke "steps.clj" 79]
#22 31.81   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 29]
#22 31.81   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 14]
#22 31.81   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 17]
#22 31.81   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 14]
#22 31.81   [clojure.lang.AFn applyToHelper "AFn.java" 154]
#22 31.81   [clojure.lang.AFn applyTo "AFn.java" 144]
#22 31.81   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.81   [clojure.core$apply invokeStatic "core.clj" 667]
#22 31.81   [clojure.core$apply invoke "core.clj" 662]
#22 31.81   [clojure.run.exec$exec invokeStatic "exec.clj" 48]
#22 31.81   [clojure.run.exec$exec doInvoke "exec.clj" 39]
#22 31.81   [clojure.lang.RestFn invoke "RestFn.java" 423]
#22 31.81   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
#22 31.81   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
#22 31.81   [clojure.run.exec$_main doInvoke "exec.clj" 139]
#22 31.81   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.81   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.81   [clojure.core$apply invokeStatic "core.clj" 667]
#22 31.81   [clojure.main$main_opt invokeStatic "main.clj" 514]
#22 31.81   [clojure.main$main_opt invoke "main.clj" 510]
#22 31.81   [clojure.main$main invokeStatic "main.clj" 664]
#22 31.81   [clojure.main$main doInvoke "main.clj" 616]
#22 31.81   [clojure.lang.RestFn applyTo "RestFn.java" 137]
#22 31.81   [clojure.lang.Var applyTo "Var.java" 705]
#22 31.81   [clojure.main main "main.java" 40]]}
#22 31.81   Step "Build driver :sparksql-databricks (edition = :oss, options = {:project-dir \"/build/driver\", :target-dir \"./target\"})" failed with error nil
#22 31.81 What would you like to do?
#22 31.81 [T]ry this step again
#22 31.81 [F]ail -- pass the failure of this step to the parent step (which can be retried)
#22 31.81 [S]kip this step
#22 31.81 [R]EPL -- open a REPL so you can debug things
#22 31.81 [Q]uit the build script (or return to the top level if running from the REPL) [T/F/S/R/Q] Execution error (NullPointerException) at metabuild-common.input/read-line-with-prompt (input.clj:28).
#22 31.89 null
#22 31.89 
#22 31.89 Full report at:
#22 31.89 /tmp/clojure-3741889775974400569.edn
------
executor failed running [/bin/sh -c clojure -X:dev:build :project-dir "\"$(pwd)\""]: exit code: 1
`

**Comment by bjgbeelen** [comment]
@zawlazaw this should work now!
