### ISSUE TITLE
New query builder datetime functions in Metabase v0.45 not supported

### ISSUE THREAD

**Issue by ValdarT** [relferreira/metabase-sparksql-databricks-driver#9]
New datetime functions in the query builder introduced in [Metabase v0.45](https://www.metabase.com/releases/Metabase-0.45) are not working. Inheriting form the official Spark driver is probably the easiest fix.

**Comment by relferreira** [comment]
Hello @ValdarT, sorry for the delay.
I've tested the driver on Metabase v0.45.1, and it seems to be working.
What date operation did you test?

![image](https://user-images.githubusercontent.com/4078815/209223579-3ae41f0b-0cad-4252-917b-47cf60f14c13.png)

**Comment by ValdarT** [comment]
Works for me, too, now. Not sure what changed. Sorry for the noise

**Comment by relferreira** [comment]
That's ok, thank you for the response and sorry again for the delay
